### ISSUE TITLE
interpolation.cpp crashes

### ISSUE THREAD

**Issue by kristopolous** [scratchapixel/scratchapixel-code#3]
There seems to be a number of interesting issues here:

https://github.com/scratchapixel/scratchapixel-code/blob/main/interpolation/interpolation.cpp#L183 which as of this writing is:

```
#define IX(size, i, j, k) ( i * j * k * size + i * j * size + i )
```

You're going to overflow your structure with this. Since `i,j,k` max is `size`, then the loop will stop at `size^4 + size^2 + size` in indexing `size^3`. You probably want something like this instead:

```
#define IX1(size, i, j, k) ( k * size * size + j * size + i )
```

Beyond that, there appears to be a double free error in the trilinear interpolation. This can be fixed as follows:

```
for (int k = 0; k < numVertices; ++k) {
   for (int j = 0; j < numVertices; ++j) {
      for (int i = 0; i < numVertices; ++i) {
```

Finally, the `e, f, g` triplet that's computed doesn't go anywhere (here: https://github.com/scratchapixel/scratchapixel-code/blob/main/interpolation/interpolation.cpp#L229), maybe you intended to write it to a file? I understand there's no simple 3D ppm format (which is kind of a crazy oversight) so perhaps just doing the slices. Is the right way. I have that in a PR I'm going to be opening shortly after this comment

Also the code https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/interpolation/bilinear-filtering.html has a syntactic error:

```
#if 1
    float  a = c00 * (1 - tx) + c10 * tx;
    float  b = c01 * (1 - tx) + c11 * tx;
    return a * (1) - ty) + b * ty;
#else
```

That block won't compile. There's a parenthesis missing.

**Comment by scratchapixel** [comment]
> On 9 Jun 2024, at 02:02, chris mckenzie ***@***.***> wrote:
> 
> #define IX(size, i, j, k) ( i * j * k * size + i * j * size + I )
This one is rather mad. This program was never tested but clearly not sure how this even got there). Pretty sad to see. Thanks for pointing this out. I will update the code tomorrow.

**Comment by scratchapixel** [comment]
Haven't seen that one in the original program though

`return a * (1) - ty) + b * ty;`

I have corrected the other ones.

As for `e,f,g` yes you are right. As you can see this code doesn't use the grid data, and that's why the  bugs were in there, since effectively, apart from verifying the code did compile, there isn't a way of checking it doesn't the right thing, hence the bugs). And clearly it wasn't tested for mem leaks & bad addresses. When this lesson was written the lesson on Volume Rendering didn't exist. Now that it does, and while some work would be necessary on the lesson on volume rendering, I should link the two.

Thanks again for your input.

**Comment by scratchapixel** [comment]
Hi Chris. Thanks again. I took the opportunity to revamp the code again, and change the variable names a bit and the logic to be sure it was as self-explanatory as possible (when reading the code). There were some issues left with overflows etc. which are hopefully all covered now. I would appreciate if you could pull the changes and have a look yourself that it all seems good to you. Thanks again for your input.

**Comment by kristopolous** [comment]
No problem. My github notices are basically an unmitigated flood so sorry I don't check them. Glad to help.
